{
 "title": "F00070* Throughput Tests",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Hosts", "query": "r.host" }
  ]
 },
 "panels": [
  {
   "title": "Ping Test to * Platform iPerf Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Min. Response Time, ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"ping\" and r._field == \"minimum_response_ms\" and r.host == \"F00070*\" and r.url == \"192.168.100.*\" )\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Max. Response Time, ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"ping\" and r._field == \"maximum_response_ms\" and r.host == \"F00070*\" and r.url == \"192.168.100.*\" )\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Avg. Response Time, ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"ping\" and r._field == \"average_response_ms\" and r.host == \"F00070*\" and r.url == \"192.168.100.*\" )\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Packet Loss, %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"ping\" and r._field == \"percent_packet_loss\" and r.host == \"F00070*\" and r.url == \"192.168.100.*\" )\r\n\r\n|> aggregateWindow(every: 10m, fn: mean)"
    }
   ]
  },
  {
   "title": "Last Packets Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"ping\" and r._field == \"packets_received\" and r.host == \"F00070*\" and r.url == \"192.168.100.*\" )\r\n\r\n|> aggregateWindow(every: 10m, fn: mean)"
    }
   ]
  },
  {
   "title": "TTL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"ping\" and r._field == \"ttl\" and r.host == \"F00070*\" and r.url == \"192.168.100.*\" )\r\n\r\n|> aggregateWindow(every: 10m, fn: mean)"
    }
   ]
  },
  {
   "title": "Standard Deviation, ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"ping\" and r._field == \"standard_deviation_ms\" and r.host == \"F00070*\" and r.url == \"192.168.100.*\" )\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Last Packets Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"ping\" and r._field == \"packets_transmitted\" and r.host == \"F00070*\" and r.url == \"192.168.100.*\" )\r\n\r\n|> aggregateWindow(every: 10m, fn: mean)"
    }
   ]
  },
  {
   "title": "TCP Test to * Platform iPerf Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Sent, Mbits/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"iperf3-F00070*-tcp\" and r._field == \"end_sum_sent_bits_per_second\" and r.host == \"F00070*\")\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Last sent, Mbits/sec",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"iperf3-F00070*-tcp\" and r._field == \"end_sum_sent_bits_per_second\" and r.host == \"F00070*\")\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Received, Mbits/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"iperf3-F00070*-tcp\" and r._field == \"end_sum_received_bits_per_second\" and r.host == \"F00070*\")\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Last received, Mbits/sec",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"iperf3-F00070*-tcp\" and r._field == \"end_sum_received_bits_per_second\" and r.host == \"F00070*\")\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Sent Data, Mbytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -14d)\r\n|> filter(fn: (r) => r._measurement == \"iperf3-F00070*-tcp\" and r._field == \"end_sum_sent_bytes\" and r.host == \"F00070*\")\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Received Data, Mbytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -14d)\r\n|> filter(fn: (r) => r._measurement == \"iperf3-F00070*-tcp\" and r._field == \"end_sum_received_bytes\" and r.host == \"F00070*\")\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Sent Retrasmits, Packets/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -14d)\r\n|> filter(fn: (r) => r._measurement == \"iperf3-F00070*-tcp\" and r._field == \"end_sum_sent_retransmits\" and r.host == \"F00070*\")\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "UDP Test to * Platform iPerf Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "Jitter, ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -14d)\r\n|> filter(fn: (r) => r._measurement == \"iperf3-F00070*-udp\" and r._field == \"end_sum_jitter_ms\" and r.host == \"F00070*\")\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Last Jitter, ms",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"iperf3-F00070*-udp\" and r._field == \"end_sum_jitter_ms\" and r.host == \"F00070*\")\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Last Packet Loss",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"iperf3-F00070*-udp\" and r._field == \"end_sum_lost_packets\" and r.host == \"F00070*\")\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Last Packets sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"iperf3-F00070*-udp\" and r._field == \"end_sum_packets\" and r.host == \"F00070*\")\r\n\r\n|> yield()"
    }
   ]
  },
  {
   "title": "Test speed, Mbits/sec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket:\"iperf\")\r\n\r\n|> range(start: -72h)\r\n|> filter(fn: (r) => r._measurement == \"iperf3-F00070*-udp\" and r._field == \"end_sum_bits_per_second\" and r.host == \"F00070*\")\r\n\r\n|> yield()"
    }
   ]
  }
 ]
}